cabal-version:      3.12
name:               hcc
version:            0.1.0.0
license:            NONE
author:             Hugo Carter
maintainer:         hjc25@ic.ac.uk
build-type:         Simple
extra-doc-files:    README.md

-- A single shared block for dependencies, language version, and flags
common shared
    ghc-options:      -Wall
    default-language: Haskell2010
    build-depends:    base ^>=4.18.3.0

library
    import:           shared
    exposed-modules:  Tokeniser Types Parser
    hs-source-dirs:   src

executable hcc
    import:           shared
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    hcc

test-suite hcc-test
    import:           shared
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    other-modules:    TestSuite TestTypes TokeniserTest ParserTest
    hs-source-dirs:   test
    build-depends:    hcc